## Jekyll build settings
markdown: kramdown
highlighter: none
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: mathjax

## Theme (keep in sync with epiconnector.github.io)
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: NHANES
description: Understanding and Analyzing NHANES Data


